title: Welcome to Flexton
description: Flexton is a responsive and ultra-minimal theme for Jekyll.



# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
